### ISSUE TITLE
Execution of business processes is possible without a registered company

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#110]
It is possible to trigger business processes before a company is registered (see screenshot).

![image](https://user-images.githubusercontent.com/2677628/42155031-90066b90-7de7-11e8-876d-3151b284601c.png)

**Comment by oliver-jung** [comment]
@hspotorno @Mytrill 

You can run role-based checks by importing the AppComponent and calling this.appComponent.checkRoles(ROLE).

Those role checks should be applied throughout the whole UI.

Currently available roles/states are:
- "reg_comp": No active company / allowed to register a company
- "wait_comp": Waiting for company approval
- "sales": Allowed to monitor sales
- "purchases": Allowed to monitor purchases
- "catalogue": Allowed to manage the company catalogue
- "bp": Allowed to execute business processes (relevant for this issue)
- "track": Allowed to use the Track'n'Trace feature
- "comp": Allowed to manage the company
- "pm": Platform Manager
- "legal": Legal representative of the company

**Comment by oliver-jung** [comment]
@hspotorno The checkRoles function does already take all those considerations into account. e.g. the role "bp" checks for the roles company_admin, external_representative, legal_representative, purchaser and sales_offices. So this.appComponent.checkRoles("bp") will unlock the business processes for everyone that is eligable to do business for their company. "sales", "purchases" and "catalogue" can be used for showing/hiding the corresponding tabs in the dashboard while "bp" can be used to enable/disable the associated BP buttons in the table. Those logical checks are in place in the "old" UI so simply take a look at the master/staging branch :)

**Comment by hspotorno** [comment]
Understood, thanks @oliver-jung!

So I kept the checks used in the old UI, and added the following:
Without "bp" permission the user can't see the business processes buttons and the negotiate button is disabled.
Without "purchases" permission the user can't see the "purchases" tab on the dashboard.
Without "sales" permission the user can't see the "sales" tab on the dashboard.
Without "catalogue" permission the user can't publish new products, and they can't see the "catalogue" tab on the dashboard (there is no longer a "catalogue" on the menu).
Without "comp" permission the user can't see the "Company Settings" page. 

This is what made sense, to me, given the roles descriptions. Let me know if you want any of them to be applied differently.
