### ISSUE TITLE
fix presentation of category values in product overview 

### ISSUE THREAD

**Issue by jpereira71** [nimble-platform/frontend-service#112]
![Screen Shot 2018-07-05 at 12.10.31.png](https://images.zenhubusercontent.com/5af9346e4b5806bc2bd2fd3b/164461bd-7cd5-439d-a7c8-229132bac9e2)

**Comment by hspotorno** [comment]
Fixed with the latest commit on V2 ![Screen Shot 2018-07-05 at 14.48.08.png](https://images.zenhubusercontent.com/5b1676fcb0890f539019b8b5/ec3f47ef-bcee-4b92-abc1-bfa8263cb3af)
