### ISSUE TITLE
Update product publish page for transportation services

### ISSUE THREAD

**Issue by Mytrill** [nimble-platform/frontend-service#113]
The product publish page (and category selection page) should be updated to support publishing of transportation services, in particular:
- on select transport service category, hide product categories (and vice versa) to make sure it is not possible to publish a product with a service category AND a product category
- if a transport service category is selected, show the editable details for transport service instead of product.

**Comment by Mytrill** [comment]
This should not require any back-end changes.

Estimate: 2 days

**Comment by hspotorno** [comment]
@oliver-jung @jinnerbichler We should have a service change to hide the logistics categories from the category search if other categories are selected (or hide all categories except logistics if that one is selected)

**Comment by hspotorno** [comment]
Following the discussion today, I will be creating a separate page for logistics products

**Comment by suatgonul** [comment]
Extended the category retrieval service enabling filtering the results for logistics or regular products:
Documentation available at: http://nimble-staging.salzburgresearch.at/catalog/swagger-ui.html#!/product-category-controller/getCategoriesUsingGET
Note the `forLogistics` parameter

**Comment by hspotorno** [comment]
Thanks, @suatgonul ! As it stands, if you're publishing a product you can still find the logistics categories. Is this correct?

**Comment by suatgonul** [comment]
Yes, I have not changed the front-end. 
The category search mechanism is still the same except that if you specify a value to the `forLogistics` parameter, the results are filtered accordingly.
