### ISSUE TITLE
Update product details page for transportation services

### ISSUE THREAD

**Issue by Mytrill** [nimble-platform/frontend-service#114]
In this issue, we update the product details page in case of services:
 - remove the pictures
 - update the tabs at the bottom
 - create simplified "Order" screen on the right

**Comment by Mytrill** [comment]
No changes required in the back-end

Estimate: 3 days.

**Comment by hspotorno** [comment]
@suatgonul @jinnerbichler I think we would need to make a change to the backend so we can track if a product was published as a logistics service or as a regular product. What do you guys think?

**Comment by suatgonul** [comment]
We were using the `transportationServiceDetails` field of `Item`. We were regarding an item as a TransportService if the

**Comment by hspotorno** [comment]
Yup, that works for me. Thanks Suat!
