### ISSUE TITLE
Reference the company details page in the product details page & in the ordering workflow

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#115]
e.g. to provide easy access to certificates

**Comment by Mytrill** [comment]
This can be done by adding a tab in the product details.

Estimate: 1 day

**Comment by oliver-jung** [comment]
The company details can be referenced using the router link /user-mgmt/company-details?id=[COMPANY_ID] or adding the company-details component that can be imported from /user-mgmt/company-details.component
