### ISSUE TITLE
Update product publishing with track & tracing related extensions

### ISSUE THREAD

**Issue by suatgonul** [nimble-platform/frontend-service#119]
In the "staging" version, we just have 3 additional fields in the product details tab related to t & t as shown below:

![image.png](https://images.zenhubusercontent.com/5b17c1a0c7faeb213becca1f/d5b82389-381b-4197-9180-c315c5e22e24)

**Comment by jpereira71** [comment]
Only add "Certificates" functionality. Disregard "Dimensions" for now. 
Certificates backend supports attachments.

**Comment by hspotorno** [comment]
"Certificates": 1 day
"T&T": 0.5 day

**Comment by Mytrill** [comment]
are Certificates and T&T relevant for logistics product?
  -> they are not relevant for logistics products.

there is no backend for file certificates for product (there is one for company), so product level certificates are only text fields for now?
  -> yes, text fields only for now.
