### ISSUE TITLE
Functionality to specify EPC codes for a confirmed order

### ISSUE THREAD

**Issue by suatgonul** [nimble-platform/frontend-service#120]
In order response page, users are able to associate EPC codes with the order

![image.png](https://images.zenhubusercontent.com/5b17c1a0c7faeb213becca1f/c0c5796e-10d0-4f63-a485-724cc1d75c85)

**Comment by jpereira71** [comment]
EPC codes set by producer.

**Comment by hspotorno** [comment]
Estimate: 0.5 day
