### ISSUE TITLE
Add support for multiple delivery addresses to company settings page

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#121]
The identity service provides the necessary API.
https://github.com/nimble-platform/identity-service/issues/35

API documentation: http://nimble-staging.salzburgresearch.at/identity/swagger-ui.html#!/company-settings-controller/getSettingsUsingGET

**Comment by jpereira71** [comment]
Update functionality also on the order page.

**Comment by hspotorno** [comment]
Estimate: 2 days
Includes possibility to switch between addresses on order page.
