### ISSUE TITLE
Catalogue upload (bulk) - APPEND [06Nov2017-1153]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#13]
Catalogue upload (bulk) - APPEND

1) the options append or replace are given.

The replace command will delete the full previous catalogue and replace it with a new one

Such actions should always be separated from benign (harmless) actions such as append.

2) change the label "append" to: "add new catalogue"

3) add a warning "all previous catalogues will be deleted and replaced by the new one - are you sure?" (Y-Replace/N-Cancel)

**Comment by oliver-jung** [comment]
Resolved by adding a confirmation warning for replace mode with commit 9b5f7d0
