### ISSUE TITLE
Choose product (or service) category [13Nov2017-1641]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#15]
The category filter is not friendly.
For example, I registered my company (Domina) and tryed to load our CAD software as product.
If I look for "cad software" the system works fine and extract my category, 
but if I look for "software cad" then the system does not extract anything.
Finally searching only the word "software" the system extracts an infinite list of categories, uncomfortable to read.

@wernher : This is firstly an ontology design and use problem and secondly, a search problem to do with string matching.

**Comment by oliver-jung** [comment]
The category search now offers a tree-based navigation after entering a search termin the staging branch. We might consider moving the tree-based navigation to the publish "landing page" along with the input field to offer a more direct entry point. In addition #52 will be adressed.
