### ISSUE TITLE
Crazy Load Product Behaviour [13Nov2017-1641]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#16]
While manually loading a product (using the web interface),
by mistake, I clicked the public product button twice,
the system twice inserted the product with the same "Product Identifier".

A(wb): Bug - will be will be forwarded to the developer team.

**Comment by jinnerbichler** [comment]
@wernher and @jinnerbichler: Behaviour could not be reproduced.

**Comment by oliver-jung** [comment]
Duplicate of #19
