### ISSUE TITLE
Download Template not possible [21 Dec 2017-3]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#17]
After clicking the "Download template" button, a green alert indicates "Download complete", but no file is downloaded to the local drive. Tested with Firefox browser.

**Comment by jinnerbichler** [comment]
This error occurred as well during the workshop in Bremen.

**Comment by jinnerbichler** [comment]
Could not be reproduced.

**Comment by oliver-jung** [comment]
Resolved with 481276d
