### ISSUE TITLE
Transient error while publishing products [21Dec2017-8]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#19]
(Minor interface issue) Sometimes, after pressing the "Publish" button, the page remains the same. At that time, if the button is pressed 2 or 3 times more (guessing that the function wasn't called), the product is then replicated in the catalogue, and sharing the same identifier (smile)

**Comment by oliver-jung** [comment]
The publish button cannot be pressed multiple times (is disabled while uploading) thus this issue should be solved. Please re-open in case the problem persists.
