### ISSUE TITLE
Improve UX for responding to incoming business process requests [1Jan2018-1130]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#22]
Currently, the functionality for responding to requests is hard to find for users.

You first have to click on the menu icon on the right and then click on the "Business History" option to see the details of the request. In that page, you should also see the options to respond.

![image](https://user-images.githubusercontent.com/2677628/35905314-e3d13be2-0be6-11e8-80e4-8d384d71391b.png)

**Comment by oliver-jung** [comment]
The BP page has been improved in the staging branch and will be further adressed using the Review 3.0 Sprint issues
