### ISSUE TITLE
Order List of Business Processes in Dashboard  by Date [19Jan2018-1226]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#23]
Path:

https://nimble-platform.salzburgresearch.at/nimble/frontend/#/dashboard

Description of the issue:

The information requests are not sorted properly by time.

Cause of the issue:

Probably the sorting issue relates to the date/time format. Example: 12:23:50 AM is larger than 1:17:32 PM which is larger than 1:05:22 PM.

**Comment by oliver-jung** [comment]
Could not reproduce. Entries in the dashboard should be sorted by dateTime using the 24h format

**Comment by jinnerbichler** [comment]
Use moment.js in order to sort by actual date.

**Comment by oliver-jung** [comment]
Resolved with commit d121841
