### ISSUE TITLE
Automatically redirect to login screen if user is not logged in

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#24]
How to reproduce:

1. Open a fresh browser (or a tab in private mode), so you are not logged in anymore.
2. Go to https://nimble-platform.salzburgresearch.at/nimble/frontend/#/user-mgmt/company-settings

This should show the login screen instead of the actual page.
It may also save the requested URL and opens the requested page after a successful login.

**Comment by oliver-jung** [comment]
Resolved with commit 602893c
