### ISSUE TITLE
Facets related to quantity values should be unified

### ISSUE THREAD

**Issue by dogukan10** [nimble-platform/frontend-service#40]
Facets related to quantity values (a value and an associated unit) should be combined into to the same panel. The current visualization hinders intuitive filtering.

For example:
- item_estimated_delivery_time and item_estimated_delivery_time_unit
![item_estimated_delivery_time](https://user-images.githubusercontent.com/30176031/38426899-7fe184cc-39c0-11e8-87d9-346e4a7086ba.png)
-  item_package_amount and item_package_amount_unit
![item_package_amount](https://user-images.githubusercontent.com/30176031/38426909-87010a3e-39c0-11e8-98e6-3190a2ab1d76.png)
- Total_capacity and total_capacity_unit
![total_capacity](https://user-images.githubusercontent.com/30176031/38426913-89921f36-39c0-11e8-8e44-0bbb2fc512c9.png)

**Comment by oliver-jung** [comment]
This is a matter of search core definitions.

Ultimately, it would also be crucial to use standardized units to properly support internationalization and range searches.

The following value/unit pairs are currently affected:
- item_price, item_price_currency
- item_estimated_delivery_time, item_estimated_delivery_time_unit
- item_package_amount, item_package_amount_unit
- total_capacity, total_capacity_unit
- estimated_duration, estimated_duration_unit

**Comment by suatgonul** [comment]
Besides the 5 pairs listed above, there can also be dynamic facets corresponding to the quantity-typed custom properties of products.

**Comment by suatgonul** [comment]
My previous comment was wrong. Currently, the custom product properties with quantity types are transformed into index fields such that the name of the field would be "property_name+unit" e.g. heightCm or heightMm. We can combine those into the same facet pane as shown below? 

![image](https://user-images.githubusercontent.com/1186287/38882331-82151442-4272-11e8-9ac3-f817e2fb16f9.png)

**Comment by oliver-jung** [comment]
Will be covered by issue #54
