### ISSUE TITLE
Improvement of business process execution views and flows

### ISSUE THREAD

**Issue by dogukan10** [nimble-platform/frontend-service#41]
This is a summarizing issue covering some previous issues about the complex / confusing characteristics of views where users start business processes, see incoming request and respond to incoming requests. I attach photos about views those were criticized before or I personally don't like and ask opinion about alternatives.

![image](https://user-images.githubusercontent.com/1186287/38428831-6da7c406-39c5-11e8-8626-c6dd88b476a9.png)

--------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/1186287/38429137-3cda4258-39c6-11e8-9cad-8fcea73521c6.png)

--------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/1186287/38429824-333cc2fa-39c8-11e8-99e1-3b22e406281b.png)

 @oliver-jung could you please have a look at this? Thanks

**Comment by oliver-jung** [comment]
Issue has been split up during the Release 3.0 Sprint planning and will be implemented according to the mockups by @Mytrill and @hspotorno
