### ISSUE TITLE
Limit field and file sizes on the front-end

### ISSUE THREAD

**Issue by oliver-jung** [nimble-platform/frontend-service#43]
Employ the catalogue service size limits on the front-end in order to avoid server-side errors.

Proposed limits:
Text properties: 2047 chars
Other properties: 255 chars
Images: 2MB
Other files: 10MB

Images might also get compressed on the client-side by converting to 80% quality JPEG and applying a maxWidth/maxHeight.

Libraries worth considering:
https://www.npmjs.com/package/fileapi
https://www.npmjs.com/package/fine-uploader
https://www.npmjs.com/package/blueimp-file-upload

**Comment by suatgonul** [comment]
I've changed the column types of item_type.name_, item_type.description and item_property_type_value_item.item (product name, product description and product feature value) fields from varchar(255) to text with 9a4b6b38bc2caa5350cf3c978f12e3c7585bb3eb

All other text-based fields have 255 chars limit now. If need other fields to keep longer values, we can deal with that afterwards

**Comment by oliver-jung** [comment]
Total: 2 days
