### ISSUE TITLE
Extended Enduser Dashboard

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#44]
- New tab for catalogue
- Redo empty dashboard for new users
- Help screen for onboarding processes
- Redo empty sales and purchases tabs
- Changes to the content of each tab (Sales / Purchases)

**Comment by Mytrill** [comment]
Tasks:
 - overall improvements & rewrite -> 1 day
 - new static page for register company -> 0.25 days
 - new static page for onboarding (sales/purchases/catalog) -> 0.25 days
 - sales tab: redesign the cards, reorder, enhance search   -> 0.5 days
 - purchases tab: redesign the cards, reorder, enhance search   -> 0.5 days
 - catalogue tab: move catalogue & redesign -> 2 days

Total: 3.5 days
