### ISSUE TITLE
Analytics in Enduser Dashboard

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#45]
TBD: what content can be reused from the platform manager dashboard?

Metrics may include:
- No. transactions
- No. of products never ordered
- Trading volume on the platform per company
- The ratio of uncompleted business processes per company (initiated/received)
- No. of searched products

**Comment by Mytrill** [comment]
**/!\ As we do not have sufficient requirements, this is a very rough estimate. /!\**

Tasks:
 - New page/tab in dasboard -> 1 day
 - 1 day per analyltics, 5 analytics -> 5 days

Total: 6 days

**Comment by hspotorno** [comment]
If only doing the mockups, estimate about 1 day

**Comment by jpereira71** [comment]
@suatgonul add the statistics that can be shown.

**Comment by jinnerbichler** [comment]
Documentation: http://nimble-staging.salzburgresearch.at/data-aggregation/swagger-ui.html#/aggregate-controller
