### ISSUE TITLE
Improve Single Product Upload

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#47]
Redo according to mockups.
A selection of properties should be selectable via a Dropdown list.

**Comment by Mytrill** [comment]
Tasks:
 - New popup for category details -> 1 day
 - New popup for properties details + integrate in other part of UI -> 1 day
 - Handle custom properties -> 0.5 day
 - New standard way of entering values for attribute + popup -> 1 day
 - Rework product delivery & trading terms UI -> 1 day
 - Separate transportation services details page -> 1 day

Total: 5.5 days
