### ISSUE TITLE
Common Feedback Mechanism

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#50]
E.g.
- Loading
- Success
- Error
- Next Step

**Comment by Mytrill** [comment]
Work for us here: go through all the actions and use common mechanism

Estimate: 1 day

**Comment by Mytrill** [comment]
Done for the following screens:
- [x] analytics -> platform analytics
- [x] catalogue -> category search & category tree
- [x] catalogue -> product publish
- [x] catalogue -> catalogue view
- [x] catalogue -> catalogue line
- [x] catalogue -> catalogue line panel
- [x] dashboard
- [x] product details
- [x] simple search
- [x] user management -> login
- [x] user management -> registration
- [x] user management -> company invitation
- [x] user management -> company registration
- [x] user management -> company settings (+ negotiation settings)
- [x] BP -> item information request & response
- [x] BP -> ppap steps (select, upload and download screens)
- [x] BP -> negotiation request & response
- [x] BP -> order
- [x] BP -> transport negotiation request & response
- [x] BP -> transport execution plan
