### ISSUE TITLE
Exchange Documents Functionality in every Business-Process Step

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/frontend-service#57]

**Comment by Mytrill** [comment]
@oliver-jung requires back-end/services change

Tasks:
 - create the upload/download UI -> 0.5 day
 - integrate into 3 BP steps (Ppap, negotiation, order) -> 1 day

Total: 1.5 days

**Comment by hspotorno** [comment]
This should be closed as the related issue (#36) has been closed as "Won't fix"
