### ISSUE TITLE
PPAP Certificate Automation

### ISSUE THREAD

**Issue by oliver-jung** [nimble-platform/frontend-service#58]
- Specification of PPAP level on company (and product) base
- Document upload

**Comment by Mytrill** [comment]
@oliver-jung requires back-end change

Tasks:
 - change in company edit/create UI: 1 day
 - change in single product upload UI: 1 day
 - change in product details page: 0.5 day

total: 2.5 days

**Comment by oliver-jung** [comment]
I will add the company edit/create UI changes and required service adaptations and then hand the issue over.

**Comment by oliver-jung** [comment]
The PPAP certificates are now part of the company settings.
They are listed as a certificate array containing id (for reference), name (self-assigned name/description of the certificate) and type (PPAP certificate type, e.g. "Process Flow Diagram").
Opening /company-settings/certificate/{certificateId} downloads a certificate.
See http://nimble-staging.salzburgresearch.at/identity/swagger-ui.html#/company-settings-controller for the full API description.
