### ISSUE TITLE
Manageable list of possible options for counter offers.

### ISSUE THREAD

**Issue by oliver-jung** [nimble-platform/frontend-service#68]
Selling companies should be able to set a list (company-wide) of options (e.g. Incoterms, payment means, payment terms. for the counter offer.

![image](https://user-images.githubusercontent.com/2677628/42943396-e9812ae2-8b62-11e8-9563-08ddb4638754.png)

**Comment by Mytrill** [comment]
@oliver-jung Needs model/backend/services update

Estimate takes into consideration that above updates are done, only component changes needed

Tasks:
 - in publish product page, add a tab with the payment terms (or include in current tab, see mockups) + (optional) associated discounts, use services to persist. -> 1 day
 - in company page, add supported payment terms (just tickboxes) -> 0.5 days
 - in negotiation step: only show supported payment + UI for discounts + include discounts in price calculation -> 1.5 days

Total: 3 days

**Comment by oliver-jung** [comment]
@jinnerbichler and I are going to employ the backend and service changes and then hand the issue over.

**Comment by Mytrill** [comment]
Payment terms and payments means are a white list (what is in the list should be available/shown), EXCEPT if the list is empty, in which case default to everything.
