### ISSUE TITLE
Redesign the Nimble Project website

### ISSUE THREAD

**Issue by hspotorno** [nimble-platform/frontend-service#71]
Redesign and recreate the Nimble Project website

**Comment by oliver-jung** [comment]
This issue is not exactly connected to the frontend-service as the project website is maintained separately.
In terms of time management I'd propose to give this a low priority.

**Comment by hspotorno** [comment]
Sure. Paulo will work on the design without involving the front-end team

**Comment by hspotorno** [comment]
@jinnerbichler Please let me know about the newsletter information when you have it

**Comment by hspotorno** [comment]
I have set up a test account with MailChimp so I can create all the forms for the website. Later somebody will need to change the API Key on the website to match Nimble's
