### ISSUE TITLE
Add catch error logic to form submits and display error in UI

### ISSUE THREAD

**Issue by hspotorno** [nimble-platform/frontend-service#72]
Reproduction examples pending, but sometimes after submitting a form it fails silently. Feedback should be given to the user.
Also on some cases, such as when the passwords don't match when registering, we should add error messages. This falls into the same catch error logic issue

**Comment by hspotorno** [comment]
Estimate: 0,75 day

**Comment by oliver-jung** [comment]
This is tightly linked to #50.

**Comment by Mytrill** [comment]
Work doe in #50
