### ISSUE TITLE
Dashboard: Select proper tab if another is empty

### ISSUE THREAD

**Issue by hspotorno** [nimble-platform/frontend-service#73]
When a producer logs in they should see the "Sales" tab, while a customer should see the "Purchases" tab. Should both tabs be filled, we will default to "Sales", as we assume actions there are often more pressing.

**Comment by Mytrill** [comment]
Oliver, as I am rewriting the dashboard (#44) I was going to do this at the same time (for one of the screen, I have to query purchase orders, sales orders & catalogue on ngInit, so I can do this pretty easily.

Should I assign this to myself?

**Comment by oliver-jung** [comment]
Actually I intend to migrate the "actionRequired" counters for sales and purchases from the "old" dashboard to the dashboard-threaded and use that in combination with the normal counter for the tab selection. I'll let you know as soon as the counters are in place so you can easily integrate them into the rewritten version.
