### ISSUE TITLE
Action to Duplicate a Product

### ISSUE THREAD

**Issue by hspotorno** [nimble-platform/frontend-service#74]
As discussed on the first workshop, the Piacenza use case requires users to be able to duplicate a product and request changes.

**Comment by hspotorno** [comment]
Estimate: would need to discuss with @oliver-jung. Likely around 4 days.

**Comment by oliver-jung** [comment]
At the time being we don't support private product and properties thus it is not feasible to duplicate a product - one would rather add the additional / changed properties to the existing product.
Private products and properties will be adressed at a later stage.
