### ISSUE TITLE
Disable workflow if no registered company

### ISSUE THREAD

**Issue by hspotorno** [nimble-platform/frontend-service#76]
We should limit the user experience when they don't have any registered companies

**Comment by hspotorno** [comment]
Estimate: 0,5 day

**Comment by oliver-jung** [comment]
The UX is already limited for users without a company.
The settings can be easily queried using the checkRoles() function in app.component.ts
The current restrictions have been agreed on. If there are any adjustments to be made this should be discussed with @wernher

**Comment by hspotorno** [comment]
We shouldn't have to change the restrictions. The issue now is that there are some actions the user can take but ends up on a screen where he can't take action.
eg: user can search for product, but when clicking on it gets "Failed to retrieve product details"
